chains:
  - name: osmosis-1
    type: osmosis
    numValidators: 1
    faucet:
      enabled: true
    ports:
      rest: 1313
      rpc: 26653
      faucet: 8082
  - name: gaia-1
    type: cosmos
    numValidators: 1
    faucet:
      enabled: true
    ports:
      rest: 1317
      rpc: 26657
      faucet: 8083

relayers:
  - name: osmos-gaia
    type: hermes
    replicas: 1
    chains:
      - osmosis-1
      - gaia-1

explorer:
  enabled: true
  ports:
    rest: 8080

registry:
  enabled: true
  ports:
    rest: 8081
