chains:
  - name: osmosis-test
    type: osmosis
    numValidators: 1
    faucet:
      enabled: true
    ports:
      rest: 1313
      rpc: 26653
      grpc: 9091
      faucet: 8082
  - name: gaia-test
    type: cosmos
    numValidators: 1
    faucet:
      enabled: true
    ports:
      rest: 1314
      rpc: 26654
      grpc: 9092
      faucet: 8083
relayers:
  - name: osmos-gaia
    type: hermes
    replicas: 1
    chains:
      - osmosis-test
      - gaia-test
explorer:
  enabled: true
  ports:
    rest: 8080

registry:
  enabled: true
  ports:
    rest: 8081
